Update numpy requirements
some of the functionality requires numpy>=2.0.0. Otherwise you get
```
AttributeError: module 'numpy' has no attribute 'trapezoid'
```